using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DigimonWorld2HexReader
{
    internal class CharacterTable
    {
        public static readonly Dictionary<byte, string> CharacterLookupTable = new Dictionary<byte, string>()
        {
            {0x00, "0"},
            {0x01, "1"},
            {0x02, "2"},
            {0x03, "3"},
            {0x04, "4"},
            {0x05, "5"},
            {0x06, "6"},
            {0x07, "7"},
            {0x08, "8"},
            {0x09, "9"},
            {0x0A, "A"},
            {0x0B, "B"},
            {0x0C, "C"},
            {0x0D, "D"},
            {0x0E, "E"},
            {0x0F, "F"},
            {0x10, "G"},
            {0x11, "H"},
            {0x12, "I"},
            {0x13, "J"},
            {0x14, "K"},
            {0x15, "L"},
            {0x16, "M"},
            {0x17, "N"},
            {0x18, "O"},
            {0x19, "P"},
            {0x1A, "Q"},
            {0x1B, "R"},
            {0x1C, "S"},
            {0x1D, "T"},
            {0x1E, "U"},
            {0x1F, "V"},
            {0x20, "W"},
            {0x21, "X"},
            {0x22, "Y"},
            {0x23, "Z"},
            {0x24, "a"},
            {0x25, "b"},
            {0x26, "c"},
            {0x27, "d"},
            {0x28, "e"},
            {0x29, "f"},
            {0x2A, "g"},
            {0x2B, "h"},
            {0x2C, "i"},
            {0x2D, "j"},
            {0x2E, "k"},
            {0x2F, "l"},
            {0x30, "m"},
            {0x31, "n"},
            {0x32, "o"},
            {0x33, "p"},
            {0x34, "q"},
            {0x35, "r"},
            {0x36, "s"},
            {0x37, "t"},
            {0x38, "u"},
            {0x39, "v"},
            {0x3A, "w"},
            {0x3B, "x"},
            {0x3C, "y"},
            {0x3D, "z"},
            //{0x41, "<SQUARE>"},
            {0x42, "&"},
            {0x44, "?"},
            {0x45, "!"},
            {0x46, "/"},
            {0x49, "-"},
            {0x54, ","},
            {0x55, "."},
            {0x56, "'"},
            {0x59, ":"},
            //{0x5B, "PLUS SIGN"},
            //{0xFB, "<Input X>"},
            //{0xFC, "\n<BOX>"},
            {0xFD, " "},
            //{0xFE, "<ENTER>"},
        };
    }
}
